// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXX366D6QghyAg4GQrDO0T1-3axiaswUM',
    appId: '1:49747168384:web:563cbae8ac6d5715acaa65',
    messagingSenderId: '49747168384',
    projectId: 'flutter-push-app-59b0b',
    authDomain: 'flutter-push-app-59b0b.firebaseapp.com',
    storageBucket: 'flutter-push-app-59b0b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zsSvNdv3YCQCdnn4qtDJ-RNB3NY1_Ro',
    appId: '1:49747168384:android:605debcab88c0b8cacaa65',
    messagingSenderId: '49747168384',
    projectId: 'flutter-push-app-59b0b',
    storageBucket: 'flutter-push-app-59b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJnLEuubso-bKDzdcz3EdaTqGf32olQQ',
    appId: '1:49747168384:ios:27f21f36a6fe50ccacaa65',
    messagingSenderId: '49747168384',
    projectId: 'flutter-push-app-59b0b',
    storageBucket: 'flutter-push-app-59b0b.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJnLEuubso-bKDzdcz3EdaTqGf32olQQ',
    appId: '1:49747168384:ios:27f21f36a6fe50ccacaa65',
    messagingSenderId: '49747168384',
    projectId: 'flutter-push-app-59b0b',
    storageBucket: 'flutter-push-app-59b0b.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXX366D6QghyAg4GQrDO0T1-3axiaswUM',
    appId: '1:49747168384:web:c64fc6fe645dbb1bacaa65',
    messagingSenderId: '49747168384',
    projectId: 'flutter-push-app-59b0b',
    authDomain: 'flutter-push-app-59b0b.firebaseapp.com',
    storageBucket: 'flutter-push-app-59b0b.firebasestorage.app',
  );
}
